apiVersion: v1
kind: Pod
metadata:
  name: auth
spec:
  containers:
  - name: apache
    image: docker.io/hectorvido/apache-auth
    imagePullPolicy: IfNotPresent
    envFrom:
    - secretRef:
        name: httpd-auth
    volumeMounts:
    - name: conf
      mountPath: /etc/apache2/httpd.conf
      subPath: httpd.conf
  volumes:
  - name: conf
    configMap:
      name: httpd-conf
